---
title: "Symbiont Profiless"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

samples <- read_tsv("data/hpc/pcangsd/samples.txt",col_names = c("sample_id","location","mapping_rate","mean_mapping_depth","genome_cov"))
```

```{r}
library(cowplot)

its <- read_tsv("data/hpc/its/sample_it2_div.txt") %>% 
  mutate(sample = str_replace(sample,"_merged","")) %>% 
    mutate(sample_id = str_replace(sample,"_L004","")) %>% 
    mutate(sample_id = str_replace(sample_id,"_S[0-9]+$","")) %>% 
  left_join(samples,by="sample_id") %>% 
  filter(!grepl(sample_id,pattern = "^BR_5_121"))

its_matrix <- its %>% 
  select(sample_id,prop,div) %>% 
  pivot_wider(names_from = "div",values_from = prop,values_fill = 0) %>% 
  column_to_rownames(var="sample_id") %>% as.matrix()

keep_cols1 <- colSums(its_matrix) > 1.5

keep_cols2 <-(its_matrix %>% apply(2,max))>0.2

keep_cols <- keep_cols1 | keep_cols2

library(ComplexHeatmap)
library(colorspace)

locations <- its %>% select(sample_id,location) %>% distinct() %>% pull(location)
names(locations) <- its %>% select(sample_id,location) %>% distinct() %>% pull(sample_id)

named_colors <- myCol
names(named_colors) <- c("Inshore", "North Offshore", "South Offshore")

ra <- rowAnnotation(location = locations[rownames(its_matrix)],
                    col = list(location = named_colors),
                    annotation_legend_param = list(title = ""),
                    show_legend = FALSE,
                    show_annotation_name = FALSE)

library(circlize)

col_fun = colorRamp2(c(0, 0.3, 0.5), diverging_hcl(3, palette = "Blue-Red 2"))

hm <- Heatmap(its_matrix[,keep_cols],
              right_annotation = ra,
              col = col_fun,
              show_row_names = FALSE, 
              show_column_dend = FALSE,
              heatmap_legend_param = list(title = "",title_gp = gpar(fontsize = 8)))



hm_plot <- grid.grabExpr(draw(hm, padding = unit(c(2,2,2,10),"mm")))

plot_grid(hm_plot)
ggsave2("figures/its2.png", width = 3,height = 3, dpi = 300, units = "in")

```

MDS based on d2s distances 

```{r}
wad2s <- read_tsv("data/hpc/temp_files/symbiont_d2s/wa_matrix.txt",skip = 1,col_names = FALSE) %>% 
  column_to_rownames("X1") 

colnames(wad2s) <- rownames(wad2s)

wad2s_d <- as.dist(wad2s)

mds <- cmdscale(wad2s_d)
as.data.frame(mds) %>% 
  rownames_to_column("sample_id") %>% 
  left_join(samples) %>% 
  ggplot(aes(x=V1,y=V2)) + geom_point(aes(color=location)) 
```

