---
title: "Figure 5"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rehh)
library(ggpubr)
library(ggrepel)
library(bedr)
library(cowplot)
source("scripts/color_scheme.R")
```


```{r}
ehh_sweeps <- read_rds("cache/candidate_regions_genes_ehh.rds") %>% 
    mutate(chr=str_trim(chr)) 

pbs_manhattan_data <- read_rds("cache/pbs.rds")

pbsdata <- read_tsv("data/hpc/thetastat/fst.slidingwindow.tsv",col_types = cols()) %>% 
  dplyr::select(chr,midPos,Nsites,starts_with("PBS")) %>% 
  pivot_longer(starts_with("PBS"),names_to = "population",values_to="PBS")


pbs_bed <- pbsdata %>% 
  mutate(start=midPos-5000,end=midPos+5000) %>% 
  unite("ID",chr,midPos,sep = ":", remove = FALSE) %>% 
  extract(chr,"chr",regex = "(.*).1") %>% 
  dplyr::select(chr,start,end,PBS,ID) %>% 
    as.data.frame() %>% 
  bedr.sort.region(check.chr = FALSE)


ehh_bed <- ehh_sweeps %>% 
  unite("locus",chr,start,end,remove = FALSE) %>% 
  dplyr::select(chr,start,end,pop,locus) %>% 
  as.data.frame() %>% 
  bedr.sort.region(check.chr = FALSE)


pbs_extreme_loci <- pbsdata %>% 
  filter(PBS>0.2) %>% 
  mutate(start=midPos-5000,end=midPos+5000) %>% 
  unite("ID",chr,midPos,sep = ":", remove = FALSE) %>% 
  extract(chr,"chr",regex = "(.*).1") %>% 
  dplyr::select(chr,start,end,PBS,ID) %>% 
    as.data.frame() %>% 
  bedr.sort.region(check.chr = FALSE)


dated_loci <- read_rds("cache/dated_loci.rds")

pop_names <- c("inshore"="Inshore","northoffshore"="North Offshore","southoffshore"="South Offshore")

pbs_ehh_overlapping <- bedr.join.region(pbs_extreme_loci,ehh_bed,check.chr = FALSE) %>% 
  filter(pop!=".") %>%
  mutate(population=pop_names[pop]) %>% 
  mutate(dated_locus_number = dated_loci[locus]) %>% 
  mutate(PBS=as.numeric(PBS)) %>% 
  left_join(pbs_manhattan_data,by=c("ID"="old_pos","PBS","population")) 




to_label <- pbs_ehh_overlapping %>% 
  group_by(locus,dated_locus_number,population) %>% 
  summarise(PBS=max(PBS),abs_pos=mean(abs_pos,na.rm=TRUE)) %>% 
  filter(dated_locus_number %in% c("7","20","31","37","38","40","41")) %>% 
#  filter(PBS>0.3) %>% 
  na.omit()
  

mh_plot <- pbs_manhattan_data %>% 
  filter(PBS>0) %>% 
  ggplot() + 
  geom_point(aes(x=abs_pos/1e6,y=PBS,color=as.character(scaffold_num %% 2)),size=0.1) + 
  geom_point(data = pbs_ehh_overlapping,aes(x=abs_pos/1e6),y=-0.15,color="purple",size=0.5) + 
  geom_point(data = to_label,aes(x=abs_pos/1e6,y=PBS),color="black",size=0.5) + 
  geom_label_repel(data = to_label,aes(x=abs_pos/1e6,y=PBS, label=dated_locus_number),size=2,nudge_y=0.5,nudge_x = -5) + 
  ylab("Population Branch Statistic") + xlab("Genome Position / Mb") + ylim(-0.2,NA) +
  scale_color_grey() +
  theme_bw() +
    theme(panel.grid = element_blank(),
        legend.position = "none",
        legend.text = element_text(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size=6),
        axis.title.x = element_text(size=6),
        strip.text = element_text(size=6))  + facet_wrap(~population,ncol = 1)
ggsave(mh_plot,filename = "figures/Figure5_manhattan.png",width = 4.75,height = 4)
```





```{r, results='hide'}
hap_names2pops <- function(hn){
  pops <- rep("IN",length(hn))
  sos <- grepl("RS[123]",hn)
  nos <- grepl("^AR",hn)
  ins <- (!sos & !nos)
  pops[sos]="SO"
  pops[nos]="NO"
  pops
}

get_furcation <- function(sweep_locus){
  vcf_file <- paste("data/hpc/startmrca/regions/",sweep_locus,".vcf",sep="")
  position <- sweeps_gs4 %>% filter(sweep_id==sweep_locus) %>% pull(position)

  hh <- data2haplohh(hap_file = vcf_file,
                     polarize_vcf = FALSE,
                     vcf_reader = "data.table")

  marker_index <- which(positions(hh)==position)

  hh_subset <- subset(hh, select.mrk = (marker_index2-200):(marker_index2+200))

  furcation <- calc_furcation(hh,mrk = marker_index)

  hn <- hap_names2pops(hap.names(hh))
  list(furcation,hn)
}

sweeps_gs4 <- read_rds("cache/sweep_regions.rds")

if (!file.exists("cache/furcation_data.rds")){
  furcation_data <- to_label %>% pull(locus) %>% purrr::map(get_furcation)
  names(furcation_data) <- to_label$locus
  write_rds(furcation_data,"cache/furcation_data.rds")
} else {
  furcation_data <- read_rds("cache/furcation_data.rds")
}
  
names(myCol) <- c("IN","NO","SO")

plot_fc <- function(fc_data,loc,pop){
  
  hn <- fc_data[[2]]
  hn[which(hn==pop)] <- "*"
  hn[which(hn!="*")] <- ""
  
  par(mar=c(1,1,1,1)+0.1, tcl=-0.1, mgp=c(2,0,0))
  
  plot(fc_data[[1]],hap.names = hn,
      col = c("black","grey70"),       
       cex=0.2,cex.lab=0.2,cex.main=0.5,cex.sub=0.2,cex.axis=0.4,
       main=loc,
       legend.xy.coords = "none")
}

furcation_plot_7 <- ~{
  plot_fc(furcation_data[['BLFC01000326_1550000_2150001']],"7","IN")
}

furcation_plot_38 <- ~{
  plot_fc(furcation_data[['BLFC01000770_1200000_1250001']],"38","IN")
}

furcation_plot_31 <- ~{
  plot_fc(furcation_data[['BLFC01000375_100000_450001']],"31","SO")
}


furcation_column <- plot_grid(furcation_plot_7,furcation_plot_38,ncol = 1)
ggsave(filename = "figures/Figure5_furcation.png",width=2,height=4)


plot_grid(mh_plot,furcation_column, ncol = 2, rel_widths = c(0.65,0.35),labels = c("A","B"))
ggsave("figures/Figure5.png",width = 6.75,height = 4)
```




