---
title: "Population structure on neutral sites only"
output: 
  github_document
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(ggpubr)
```

```{r}
samples <- read_tsv("data/hpc/pcangsd/samples.txt",col_names = c("sample_id","location","mapping_rate","mean_mapping_depth","genome_cov"))

sample_table <- read_tsv("data/hpc/pcangsd/all_bam.txt",col_names = "filename") %>%
  mutate(country=str_match(filename,pattern = "/fast/shared/Acropora_digitifera_wgs_bamfile/([A-Z]+)/")[,2]) %>% 
  mutate(sample = str_match(filename,pattern = "/fast/shared/Acropora_digitifera_wgs_bamfile/[A-Z]+/(.*)_aligned")[,2]) %>% 
  mutate(sample = str_replace(sample,"_merged","")) %>% 
    mutate(sample_id = str_replace(sample,"_L004","")) %>% 
    mutate(sample_id = str_replace(sample_id,"_S[0-9]+$","")) %>% 
  left_join(samples) %>% 
  mutate(location = ifelse(is.na(location),"Japan",location)) %>% 
  rownames_to_column("number")
```


Since selection analyses identified a large number of loci with strong signatures of selection, especially in the inshore population, it is possible that our estimates of population structure and divergence have been distorted by these effects.  

```{r}
covmat_all_uces <- read_table2("data/hpc/pcangsd/all_uces.cov",col_names = FALSE) %>% 
  as.matrix()

pop_eigen_uces <- eigen(covmat_all_uces)
eigenvalues_uces <- round(pop_eigen_uces$values,1)

pop_pca_uces <- data.frame(e1=pop_eigen_uces$vectors[,1],e2=pop_eigen_uces$vectors[,2]) %>% cbind(sample_table)

pclabel <- function(pcnum,eigenvalues){
  paste("PC",pcnum," (",eigenvalues[pcnum],"%)",sep = "")
}

ggplot(pop_pca_uces ,aes(x=e1,y=e2)) + 
  geom_point(aes(color=location),size=1) + 
  theme_pubr() + xlab(pclabel(1,eigenvalues_uces)) + 
  ylab(pclabel(2,eigenvalues_uces)) + 
  theme(legend.title = element_blank())
```


```{r}
library(ggtree)
library(treeio)
library(ape)

t <- read.tree("data/hpc/pcangsd/all_uces.tree")

tr <- root(t,node=133)

ggtree(tr) %<+% sample_table + 
  geom_tippoint(aes(color=location)) +
  geom_tiplab(aes(label=sample)) +
#  geom_nodelab(aes(label=node)) +
  theme(legend.title = element_blank())
```
